import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rock Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
        <link
          rel="stylesheet"
          type="text/css"
          href="/css/fontello/css/fontello.css"
        />
        <link rel="stylesheet" type="text/css" href="/css/prettyPhoto.css" />
        <link
          rel="stylesheet"
          type="text/css"
          href="/css/responsiveslides.css"
        />
        <link rel="stylesheet" type="text/css" href="/css/responsive.css" />
        <link
          href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
          rel="stylesheet"
          type="text/css"
        />

        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/Chart.min.js"></script>
        <script
          type="text/javascript"
          src="/js/jquery.flexslider.min.js"
        ></script>
        <script type="text/javascript" src="/js/jquery.prettyPhoto.js"></script>
        <script type="text/javascript" src="/js/SmoothScroll.js"></script>
        <script type="text/javascript" src="/js/responsiveslides.js"></script>
        <script type="text/javascript" src="/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="/js/_front.js"></script>
      </Head>
      <div class="no-blog">
        <div className="body_background"></div>
        <div className="panelbutton"></div>
        <div className="panel">
          <div className="columns">
            <div className="item homepages">
              <div className="title">Homepage Style</div>
              <ul>
                <li>
                  <a href="index.html" className="active">
                    rock group
                  </a>
                </li>
                <li>
                  <a href="ecogroup.html">eco group</a>
                </li>
                <li>
                  <a href="travelgroup.html">travel group</a>
                </li>
              </ul>
            </div>
            <div className="item patterns">
              <div className="title">Patterns</div>
              <ul>
                <li>
                  <div className="pattern1"></div>
                </li>
                <li>
                  <div className="pattern2"></div>
                </li>
                <li>
                  <div className="pattern3"></div>
                </li>
                <li>
                  <div className="pattern4"></div>
                </li>
                <li>
                  <div className="pattern5"></div>
                </li>
                <li>
                  <div className="pattern6"></div>
                </li>
              </ul>
            </div>
            <div className="item background">
              <div className="title">Background Image</div>
              <ul>
                <li>
                  <div className="background1"></div>
                </li>
                <li>
                  <div className="background2"></div>
                </li>
                <li>
                  <div className="background3"></div>
                </li>
                <li>
                  <div className="background4"></div>
                </li>
                <li>
                  <div className="background5"></div>
                </li>
                <li>
                  <div className="background6"></div>
                </li>
              </ul>
            </div>
            <div className="item layout">
              <div className="title">Layout Style</div>
              <div>
                <span id="boxed">boxed</span>
                <span id="wide" className="active">
                  wide
                </span>
              </div>
            </div>
          </div>
          <div className="close"></div>
        </div>
        <div className="box">
          <header id="header" className="container">
            <div className="main">
              <nav className="header">
                <ul>
                  <li>
                    <a href="/shortcodes">features</a>
                  </li>
                  <li>
                    <Link href="/about">about us</Link>
                  </li>
                  <li className="logo">
                    <a href="/">
                      <img src="images/logo.png" alt="" />
                      <h3>rock group</h3>
                      <h6>infographic theme</h6>
                    </a>
                  </li>
                  <li>
                    <a href="/blog">blog</a>
                  </li>
                  <li>
                    <a href="/gallery">portfolio</a>
                  </li>
                </ul>
              </nav>
              <nav className="header scroll_menu">
                <ul>
                  <li>
                    <a href="/shortcodes">features</a>
                  </li>
                  <li>
                    <Link href="/about">about us</Link>
                  </li>
                  <li className="logo">
                    <a href="/">
                      <img src="images/logo.png" alt="" />
                      <h3>rock group</h3>
                      <h6>infographic theme</h6>
                    </a>
                  </li>
                  <li>
                    <a href="/blog">blog</a>
                  </li>
                  <li>
                    <a href="/gallery">portfolio</a>
                  </li>
                </ul>
              </nav>
              <div id="scene_1">
                <img className="item" src="images/scene/a1.png" alt="" />
                <div id="items">
                  <div>
                    <img src="images/scene/101.png" alt="" />
                  </div>
                  <div>
                    <img src="images/scene/102.png" alt="" />
                  </div>
                  <div>
                    <img src="images/scene/103.png" alt="" />
                  </div>
                  <div>
                    <img src="images/scene/104.png" alt="" />
                  </div>
                  <div>
                    <img src="images/scene/105.png" alt="" />
                  </div>
                </div>
                <img className="item" src="images/scene/a5.png" alt="" />
                <img id="airplane" src="images/scene/6.png" alt="" />
                <div className="clouds">
                  <div id="cl_1" data-time="28" data-direction="right"></div>
                  <div id="cl_2" data-time="36" data-direction="left"></div>
                  <div id="cl_3" data-time="57" data-direction="left"></div>
                  <div id="cl_4" data-time="49" data-direction="right"></div>
                </div>
                <div className="headline">
                  <a href="" id="ln_1">
                    <span className="numder">50</span>
                    <span>Aliquam porta dui nec dapibus.</span>
                  </a>
                  <a href="" id="ln_2" className="right">
                    <span>Maecenas molestie ultrices blandit.</span>
                    <span className="numder">78</span>
                  </a>
                  <a href="" id="ln_3">
                    <span className="numder">95</span>
                    <span>Maecenas molestie ultrices blandit.</span>
                  </a>
                </div>
              </div>
              <div className="more_arrow">
                <span className="icon-down-open"></span>
              </div>
            </div>
          </header>
          <section className="container darkseagreen">
            <div className="main white">
              <h4>What is Zonta?</h4>
              <h6>
                Zonta is a type of crypto currency. Zonta Coin is a
                decentralized cryptocurrency that is built on the EOS
                blockchain. Its main goal is to provide a fast, secure, and
                cost-effective alternative to traditional payment methods. One
                of the key features of Zonta Coin is that it has zero
                transaction fees, making it an attractive option for users who
                want to send and receive payments without incurring any
                additional costs.
              </h6>
              <h6>
                Zonta Coin is a decentralized cryptocurrency built on the EOS
                blockchain that aims to revolutionize the way people transact
                online. With its zero transaction fee model, Zonta Coin is
                poised to become the preferred choice for online payments and
                micropayments.
              </h6>
              <div id="about">
                <a href="" className="item">
                  <img src="images/1.png" alt="" />
                  <span>Fully Customizable</span>
                </a>
                <div className="arrow"></div>
                <a href="" className="item">
                  <img src="images/2.png" alt="" />
                  <span>About Studio</span>
                </a>
                <div className="arrow"></div>
                <a href="" className="item">
                  <img src="images/3.png" alt="" />
                  <span>Project Team</span>
                </a>
              </div>
              <div className="open_more" data-cont="tabs">
                <div className="icon-down-open"></div>
                <span>more</span>
              </div>
            </div>
          </section>
          <section id="tabs" className="container beige">
            <div className="tabs_name darkseagreen">
              <ul>
                <li className="active">fully customizable</li>
                <li>about studio</li>
                <li>project team</li>
              </ul>
            </div>
            <div className="tabs main ">
              <div className="tab active">
                <h2>FULLY Customizable</h2>
                <div className="title">
                  RockGroup is an Infographic theme that offers infinite options
                  for creation of the unique layout for your website.
                </div>
                <div className="slider_container">
                  <ul id="slider1" className="rslides">
                    <li>
                      <img src="images/scene/14.png" alt="" />
                    </li>
                    <li>
                      <img src="images/scene/15.png" alt="" />
                    </li>
                    <li>
                      <img src="images/scene/16.png" alt="" />
                    </li>
                  </ul>
                </div>
                <div className="content gray">
                  We created three popular infographic skins for business,
                  ecology and travel. You may use these templates both for these
                  themes and for many others, since they are quite versatile.{" "}
                </div>
              </div>
              <div className="tab">
                <h2>About STUDIO</h2>
                <div className="columns_2">
                  <div className="item">
                    <div className="icon">
                      <img src="images/icons/1.png" alt="" />
                    </div>
                    <div className="content">
                      <h4 className="light black">With Love to Customers</h4>
                      <span>
                        ThemeRex is a studio that aims to make their user’s
                        experience easier and much more pleasant. You probalby
                        won’t have a better opportunity to make sure of their
                        competence, as well as friendliness towards their
                        customers. Vast experience and understanding of each
                        product’s peculiarities let ThemeRex create outstanding
                        business solutions.
                      </span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="icon">
                      <img src="images/icons/2.png" alt="" />
                    </div>
                    <div className="content">
                      <h4 className="light black">High Professionalism</h4>
                      <span>
                        Many year experience and hundreds of successful projects
                        have made ThemeRex a professional on the web area.
                        Within this period of time, the company has gone through
                        a serious evolution from amateurs to leaders. We create
                        templates for your websites that will increase your
                        reputation and highlight your professionalism and
                        leadership.
                      </span>
                    </div>
                  </div>
                </div>
                <div className="columns_2">
                  <div className="item">
                    <div className="icon">
                      <img src="images/icons/3.png" alt="" />
                    </div>
                    <div className="content">
                      <h4 className="light black">Serving Clients’ Goals </h4>
                      <span>
                        ThemeRex is doing their best to grant each owner of
                        their themes with maximum opportunities to present their
                        individuality, show their achievements, and establish
                        the best contact with their audience. Using their rich
                        experience, world’s innovations and their own web
                        solutions the ThemeRex team creates templates that will
                        solve your business’s tasks at maximum degree.
                      </span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="icon">
                      <img src="images/icons/4.png" alt="" />
                    </div>
                    <div className="content">
                      <h4 className="light black">Reliability and Prestige</h4>
                      <span>
                        Purchasing products from ThemeRex means entrusting your
                        reputation to one of the best web-studios. ThemeRex
                        company does its work with its customer in mind. That is
                        why you are getting the best product that will perfectly
                        suit your needs.
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div className="tab">
                <h2>Project TEAM</h2>
                <div className="team vertical">
                  <div className="item">
                    <div className="image">
                      <img src="images/scene/18.png" alt="" />
                      <div className="overlay">
                        <ul className="social">
                          <li>
                            <a href="https://www.facebook.com/themerex/">
                              <span className="icon-facebook"></span>
                            </a>
                          </li>
                          <li>
                            <a href="https://twitter.com/Theme_REX/">
                              <span className="icon-twitter"></span>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <span className="icon-pinterest"></span>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="content right">
                      <a href="#">
                        <h4 className="light black">Trinity</h4>
                      </a>
                      <a href="#">
                        <span>Web Designer</span>
                      </a>
                    </div>
                  </div>
                  <div className="item">
                    <div className="image">
                      <img src="images/scene/19.png" alt="" />
                      <div className="overlay">
                        <ul className="social">
                          <li>
                            <a href="https://www.facebook.com/themerex/">
                              <span className="icon-facebook"></span>
                            </a>
                          </li>
                          <li>
                            <a href="https://twitter.com/Theme_REX/">
                              <span className="icon-twitter"></span>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <span className="icon-pinterest"></span>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="content left">
                      <a href="#">
                        <h4 className="light black">Katherine</h4>
                      </a>
                      <a href="#">
                        <span>Web Developer</span>
                      </a>
                    </div>
                  </div>
                  <div className="item">
                    <div className="image">
                      <img src="images/scene/17.png" alt="" />
                      <div className="overlay">
                        <ul className="social">
                          <li>
                            <a href="https://www.facebook.com/themerex/">
                              <span className="icon-facebook"></span>
                            </a>
                          </li>
                          <li>
                            <a href="https://twitter.com/Theme_REX/">
                              <span className="icon-twitter"></span>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <span className="icon-pinterest"></span>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="content right">
                      <a href="#">
                        <h4 className="light black">Henry</h4>
                      </a>
                      <a href="#">
                        <span>Project Manager</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="open_more gray" data-cont="tabs">
              <div className="icon-down-open gray"></div>
              <span>hide</span>
            </div>
          </section>
          <section className="container pad90-top yellowgreen">
            <div className="main white">
              <h1>6231</h1>
              <h4 className="light">
                ...cups of coffee was consumed by our team in 2014. And yes,
                this figure here is for no reason.
                <br /> And we are presenting you <b>trx skills widget</b>{" "}
                specially stylized for <b>rock group</b>
              </h4>
              <div className="widget_skills">
                <div className="widget_inner">
                  <div className="skills_row">
                    <span className="value">5474</span>
                    <div className="progressbar">
                      <div className="progress" data-process="80%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                      <div className="shadow"></div>
                    </div>
                    <span className="caption">L1</span>
                  </div>
                  <div className="skills_row">
                    <span className="value">856</span>
                    <div className="progressbar">
                      <div className="progress" data-process="40%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                    </div>
                    <span className="caption">L2</span>
                  </div>
                  <div className="skills_row">
                    <span className="value">3568</span>
                    <div className="progressbar">
                      <div className="progress" data-process="70%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                    </div>
                    <span className="caption">L3</span>
                  </div>
                  <div className="skills_row">
                    <span className="value">2354</span>
                    <div className="progressbar">
                      <div className="progress" data-process="60%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                    </div>
                    <span className="caption">L4</span>
                  </div>
                  <div className="skills_row">
                    <span className="value">6231</span>
                    <div className="progressbar">
                      <div className="progress" data-process="100%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                    </div>
                    <span className="caption">L5</span>
                  </div>
                  <div className="skills_row">
                    <span className="value">1256</span>
                    <div className="progressbar">
                      <div className="progress" data-process="50%">
                        <div className="before"></div>
                        <div className="after"></div>
                      </div>
                      <div className="foot"></div>
                    </div>
                    <span className="caption">L6</span>
                  </div>
                </div>
              </div>
              <div className="open_more" data-cont="post_sdb">
                <div className="icon-down-open"></div>
                <span>more</span>
              </div>
            </div>
          </section>
          <section id="post_sdb" className="container pad90">
            <div className="main">
              <div className="image">
                <img src="images/scene/20.png" alt="" />
              </div>
              <div className="post_sdb">
                <h2>Skills Widget</h2>
                <div className="info marg60-bot">
                  Posted{" "}
                  <a href="" className="date">
                    February 25, 2014
                  </a>
                  by{" "}
                  <a href="" className="author">
                    TRX_admin
                  </a>
                  in{" "}
                  <a className="link" href="">
                    Post Formats, Post formats fullwidth
                  </a>
                </div>
                <div className="text marg60-bot">
                  To display your knowledge and skills graphically, you have a
                  specially designed widget at your disposal, such as "TRX
                  Skills". You may choose unlimited number of skills, name them,
                  set the level, color and one of the display styles.
                  <br /> Vivamus vel mauris id turpis scelerisque ullamcorper.
                  Ut non velit blandit neque aliquam finibus. Donec ornare
                  tortor ac arcu elementum fermentum. Suspendisse rhoncus est
                  vitae leo rutrum congue. Pellentesque nisl sapien, mollis sit
                  amet eros in, imperdiet tempus tortor. Nulla eu lobortis sem.
                  Mauris vitae aliquet tortor.
                </div>
                <div className="sharing marg60-bot">
                  <ul>
                    <li className="more">
                      <span className="icon icon-link"></span>
                      <span>More</span>
                    </li>
                    <li className="share">
                      <span className="icon icon-share"></span>
                      <span>Share</span>
                    </li>
                    <li className="views">
                      <span className="icon icon-eye"></span>
                      <span>153</span>
                    </li>
                    <li className="comments">
                      <span className="icon icon-comment"></span>
                      <span>1</span>
                    </li>
                    <li className="rating">
                      <span className="icon icon-star"></span>
                      <span>79.3</span>
                    </li>
                    <li className="likes">
                      <span className="icon icon-heart"></span>
                      <span>18</span>
                    </li>
                  </ul>
                </div>
                <div className="more">
                  <a href="">read more</a>
                </div>
              </div>
            </div>
          </section>
          <section id="dev_container" className="container pad90">
            <div className="main">
              <h4>How Zonta Will Revolutionize Services Sector</h4>
              <h4 className="light gray">
                Zonta Coin has the potential to revolutionize the services
                sector, particularly in the area of hedge funds. Hedge funds are
                investment vehicles that use a variety of strategies, including
                leveraging, short selling, and derivatives, to generate returns
                for their investors. However, they are often associated with
                high fees and a lack of transparency, which can make them
                unattractive to many investors.
              </h4>
              <h4 className="light gray">
                By using Zonta Coin and the EOS blockchain, hedge funds can
                offer a more cost-effective and transparent investment option to
                their clients. With zero transaction fees and real-time
                settlement, Zonta Coin can help to reduce the costs associated
                with investing in hedge funds, making them more accessible to a
                wider range of investors.
              </h4>
              <h4 className="light gray">
                Additionally, the use of smart contracts on the EOS blockchain
                can help to increase transparency and accountability in the
                hedge fund industry. Smart contracts are self-executing
                contracts with the terms of the agreement between buyer and
                seller being directly written into lines of code. This can help
                to reduce the risk of fraud or mismanagement, as all
                transactions are recorded on the blockchain and can be easily
                audited.
              </h4>
              <h4 className="light gray">
                Overall, the adoption of Zonta Coin and the EOS blockchain in
                the hedge fund industry has the potential to revolutionize the
                way that these services are provided, making them more
                cost-effective and transparent for investors.
              </h4>
              <h4 className="light gray">
                Zonta Coin has the potential to revolutionize the services
                sector by offering a stable and inflation-proof cryptocurrency.
                Inflation is a measure of the rate at which the general level of
                prices for goods and services is rising, and subsequently,
                purchasing power is falling. Central banks attempt to limit
                inflation and avoid deflation in order to keep the economy
                running smoothly.
              </h4>
              <h4 className="light gray">
                One of the key features of Zonta Coin is its zero inflation
                policy. This means that the supply of Zonta Coins is carefully
                managed through a decentralized autonomous organization (DAO),
                which allows for transparent and democratic decision-making
                about the distribution and use of the coin. This helps to ensure
                that the value of Zonta Coin remains stable over time, rather
                than being subject to the fluctuations that can occur with other
                cryptocurrencies.
              </h4>
              <h4 className="light gray">
                The stability of Zonta Coin can have a number of benefits for
                the services sector. For example, businesses that accept Zonta
                Coin as a form of payment can be more confident that the value
                of their income will not be eroded over time by inflation. This
                can help to improve financial planning and budgeting for
                businesses, as they can have a better understanding of the
                long-term value of their income.
              </h4>
              <h4 className="light gray">
                Additionally, the stability of Zonta Coin can also be attractive
                to consumers, who may be more likely to use a stable and
                reliable form of payment rather than one that is subject to
                fluctuations in value. This can help to drive adoption and usage
                of Zonta Coin in the services sector, which can lead to a more
                efficient and effective economy overall.
              </h4>
              <h4 className="light gray">
                In conclusion, the zero inflation policy of Zonta Coin has the
                potential to revolutionize the services sector by offering a
                stable and reliable form of payment that is resistant to
                inflation. This can help to improve financial planning and
                budgeting for businesses, as well as increasing confidence and
                adoption among consumers.
              </h4>
              <div>
                <div id="devices">
                  <div className="item">
                    <img src="images/ledcinema.png" alt="" />
                    <span>Retina Ready</span>
                  </div>
                  <div className="arrow"></div>
                  <div className="item">
                    <img src="images/macbook.png" alt="" />
                    <span>Tablet friendly</span>
                  </div>
                  <div className="arrow"></div>
                  <div className="item">
                    {" "}
                    <img src="images/mobile.png" alt="" />
                    <span>100% responsive</span>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="container pad90 cornsilk">
            <div className="main">
              <h4>How You Will Be Able to Swap Tokens?</h4>
              <h6>
                Swapping tokens refers to the process of exchanging one
                cryptocurrency for another. There are a number of ways that you
                can swap tokens, and the specific method you use will depend on
                your specific needs and preferences.
              </h6>
              {/* <h4 className="light gray">
                ThemeRex worked out an amazing combination of vast
                fucntionalilty and user’s comfort. Thanks to an amazingly user
                friendly TRX Framework, customers have a chance to customize
                their theme the way they like.{" "}
              </h4> */}
              <h4 className="light gray">
                One way to swap tokens with zero payment fees is to use a
                decentralized exchange (DEX). A DEX is a cryptocurrency exchange
                that is built on a decentralized platform, such as the Ethereum
                blockchain. This means that it is not controlled by a single
                centralized entity, and users can trade directly with each other
                without the need for intermediaries. <br />
                To use a DEX to swap tokens with zero payment fees, you will
                need to have a wallet that is compatible with the DEX and the
                cryptocurrencies you want to trade. You will also need to have
                some of the tokens that you want to exchange in your wallet.{" "}
                <br />
                Once you have set up your wallet and have the required tokens,
                you can use the DEX to search for a trade that meets your
                specific needs. This will typically involve specifying the
                tokens you want to trade, the amount you want to trade, and the
                price you are willing to pay or accept. <br />
                Once you have found a trade that meets your requirements, you
                can initiate the swap by placing an order on the DEX. The tokens
                will then be exchanged between your wallet and the
                counterparty's wallet, and the trade will be completed. <br />
                In conclusion, you can use a DEX to swap tokens with zero
                payment fees by setting up a compatible wallet and using the DEX
                to find and initiate a trade. This can be a convenient and
                cost-effective way to exchange tokens without incurring any
                additional fees.
              </h4>
              <div className="diagram_skills resp marg90">
                <div className="title">
                  <span className="number">100%</span>result
                </div>
                <div id="sk_1" className="sc_skills">
                  <canvas
                    id="canvas_sk_1"
                    height="520"
                    width="520"
                    data-percent="25"
                    data-color="#c0c192"
                  ></canvas>
                  <div className="line">
                    <div className="tail"></div>
                  </div>
                  <div className="item">
                    <img src="images/7.png" alt="" />
                    <span>100% Responsive</span>
                    <div className="content">
                      The fact of prevalence of mobile devices obliges to adjust
                      any actual website to their peculiarity at maximum degree.
                    </div>
                  </div>
                </div>
                <div id="sk_2" className="sc_skills">
                  <canvas
                    id="canvas_sk_2"
                    height="460"
                    width="460"
                    data-percent="50"
                    data-color="#c44b12"
                  ></canvas>
                  <div className="line">
                    <div className="tail"></div>
                  </div>
                  <div className="item">
                    <img src="images/6.png" alt="" />
                    <span>Free Support</span>
                    <div className="content">
                      Our Support Team is ready to become your reliable guide in
                      the World of RockGroup. We provide free access to theme
                      Documentation and our Ticket Sys.
                    </div>
                  </div>
                </div>
                <div id="sk_3" className="sc_skills">
                  <canvas
                    id="canvas_sk_3"
                    height="400"
                    width="400"
                    data-percent="75"
                    data-color="#669c75"
                  ></canvas>
                  <div className="line">
                    <div className="tail"></div>
                  </div>
                  <div className="item">
                    <img src="images/5.png" alt="" />
                    <span>Shortcodes</span>
                    <div className="content">
                      Rock Group includes the most full set of Shortcodes,
                      amongst which you can find those you can get only in
                      ThemeRex products.
                    </div>
                  </div>
                </div>
                <div id="sk_4" className="sc_skills">
                  <canvas
                    id="canvas_sk_4"
                    height="340"
                    width="340"
                    data-percent="85"
                    data-color="#3d9ba9"
                  ></canvas>
                  <div className="line">
                    <div className="tail"></div>
                  </div>
                  <div className="item">
                    <img src="images/4.png" alt="" />
                    <span>SEO Ready</span>
                    <div className="content">
                      HTML5 code integrated into the theme meets the best SEO
                      approaches. The theme supports compatibility with
                      advaneced SEO plugins.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="container pad90-top beige">
            <div className="main">
              <h4>trx framework</h4>
              <h6>Combination of vast functionality and user’s comfort!</h6>
              <div id="framework">
                <div className="item left">
                  <ul>
                    <li>
                      <a href="">
                        Unique Setting Inheritance
                        <br /> and Override System
                      </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                    <li>
                      <a href="">
                        Shortcode Builder
                        <br /> or Visual Composer{" "}
                      </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                    <li>
                      <a href="">
                        Raiting \ Review Mechanism
                        <br /> and Media Content Manager{" "}
                      </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                  </ul>
                </div>
                <div className="item">
                  <img src="images/scene/7.png" alt="" />
                </div>
                <div className="item right">
                  <ul>
                    <li>
                      <a href="">
                        Raiting \ Review Mechanism
                        <br /> and Media Content Manager{" "}
                      </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                    <li>
                      <a href="">PO Composer </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                    <li>
                      <a href="">
                        Unique Setting Inheritance
                        <br /> and Override System{" "}
                      </a>
                      <div className="line">
                        <div className="head"></div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </section>
          <section className="container pad90-top skyblue">
            <div className="main">
              <h4 className="light white">
                Common settings can be overriden for any page/category/post. For
                instance, you can assign your own set of parameters for each
                category: color scheme, sidebars, menu type, style of slider and
                many more.
              </h4>
              <div className="open_more" data-cont="video">
                <div className="icon-down-open"></div>
                <span>more</span>
              </div>
            </div>
          </section>
          <section id="video" className="container skyblue">
            <div className="main">
              <div className="video_container">
                <div
                  className="video_thumb"
                  data-frame="http://player.vimeo.com/video/105286558"
                ></div>
              </div>
              <div className="content large white">
                TRX Framework It is a result of accumulated experience of
                WordPress themes development and constant contact with
                customers.
                <br /> It worked out an amazing combination of vast
                functionality and user’s comfort. Thanks to an amazingly user
                friendly TRX Framework,
                <br /> customers have a chance to customize their theme the way
                they like.{" "}
              </div>
              <div className="open_more" data-cont="video">
                <div className="icon-down-open"></div>
                <span>more</span>
              </div>
            </div>
          </section>
          <section id="diagram_skills_2" className="container seagreen">
            <div className="main">
              <div id="scene_2">
                <div id="ship">
                  <img src="images/scene/s1.png" alt="" />
                </div>
                <div className="wave left"></div>
                <div className="wave right"></div>
              </div>
              <div className="skills_container">
                <div className="diagram_skills" data-cutout="90">
                  <div className="title">
                    <span className="number">13</span>
                  </div>
                  <div id="sd_1" className="sc_skills">
                    <canvas
                      id="canvas_sd_1"
                      height="180"
                      width="180"
                      data-percent="80"
                      data-color="#ffffff"
                    ></canvas>
                    <div className="name">psd</div>
                  </div>
                </div>
                <div className="diagram_skills" data-cutout="90">
                  <div className="title">
                    <span className="number">2</span>
                  </div>
                  <div id="sd_2" className="sc_skills">
                    <canvas
                      id="canvas_sd_2"
                      height="180"
                      width="180"
                      data-percent="40"
                      data-color="#ffffff"
                    ></canvas>
                    <div className="name">drupal</div>
                  </div>
                </div>
                <div className="diagram_skills" data-cutout="90">
                  <div className="title">
                    <span className="number">10</span>
                  </div>
                  <div id="sd_3" className="sc_skills">
                    <canvas
                      id="canvas_sd_3"
                      height="180"
                      width="180"
                      data-percent="75"
                      data-color="#ffffff"
                    ></canvas>
                    <div className="name">wp</div>
                  </div>
                </div>
                <div className="diagram_skills" data-cutout="90">
                  <div className="title">
                    <span className="number">7</span>
                  </div>
                  <div id="sd_4" className="sc_skills">
                    <canvas
                      id="canvas_sd_4"
                      height="180"
                      width="180"
                      data-percent="65"
                      data-color="#ffffff"
                    ></canvas>
                    <div className="name">html</div>
                  </div>
                </div>
              </div>
              <div id="scene_3"></div>
            </div>
          </section>
          <section className="container pad90-top seagreen">
            <div className="main white">
              <h4>some facts about us</h4>
              <h6>
                rock group gives you an option to create an infinite number of
                layout types.
              </h6>
              <div id="widget_2" className="widget_skills">
                <div className="widget_inner">
                  <a href="" id="lw_1" className="skills_row">
                    <img src="images/scene/12.png" alt="" />
                    <div className="name">Css3</div>
                  </a>
                  <a href="" id="lw_2" className="skills_row">
                    <img src="images/scene/11.png" alt="" />
                    <div className="name">Html5</div>
                  </a>
                  <a href="" id="lw_3" className="skills_row">
                    <img src="images/scene/10.png" alt="" />
                    <div className="name">MySql</div>
                  </a>
                  <a href="" id="lw_4" className="skills_row">
                    <img src="images/scene/9.png" alt="" />
                    <div className="name">pHp</div>
                  </a>
                  <a href="" id="lw_5" className="skills_row">
                    <img src="images/scene/13.png" alt="" />
                    <div className="name">Design</div>
                  </a>
                </div>
              </div>
            </div>
          </section>
          <section className="container pad90-top cadetblue">
            <div className="main">
              <a
                href="http://themeforest.net/item/rock-group-multipurpose-infographic-theme/9005879"
                className="button anim"
              >
                purchase
              </a>
              <h4 className="light white marg0">
                ThemeRex is doing their best to grant each owner of Rock Group
                with maximum opportunities
                <br /> to present their individuality, and establish the best
                contact with their audience.
              </h4>
            </div>
          </section>
          <footer className="footer container cadetblue">
            <div className="main white">
              <div className="logo">
                <img src="images/logo.png" alt="" />
                <h3>rock group</h3>
                <h6>infographic theme</h6>
              </div>
              <div className="content">
                <a href="http://themeforest.net/user/ThemeREX?WT.ac=item_profile_text&WT.z_author=ThemeREX">
                  ThemeREX
                </a>{" "}
                © 2014. All Rights Reserved.{" "}
                <a href="http://themeforest.net/user/ThemeREX/portfolio?WT.ac=portfolio_item&WT.z_author=ThemeREX">
                  Terms of Use
                </a>{" "}
                and <a href="">Privacy Policy</a>.
              </div>
              <div className="social">
                <ul>
                  <li>
                    <a href="">
                      <span className="icon-facebook"></span>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <span className="icon-twitter"></span>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <span className="icon-pinterest"></span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </>
  );
}
